import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Providers from "./provider";
import LeftSidebar from "@/components/shared/LeftSidebar";
import BottomSidebar from "@/components/shared/BottomSidebar";
import TopSidebar from "@/components/shared/TopSidebar";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TodoDash",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <main className="flex">
            <TopSidebar />
            <LeftSidebar />

            <section className="main-container">
              <div className="w-full max-w-4xl">
                <Providers>
                  {children}
                </Providers>
              </div>
            </section>

            <BottomSidebar />
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
